style:
  MagicNumber:
    active: false
  MaxLineLength:
    active: true
    maxLineLength: 140
  ReturnCount:
    active: false

complexity:
  LongMethod:
    active: true
    allowedLines: 90
  TooManyFunctions:
    active: false

exceptions:
  TooGenericExceptionCaught:
    active: false

naming:
  FunctionNaming:
    active: false
